name: Build em_proxy

on: [push]

jobs:
  build:
    name: Build em_proxy
    if: startsWith(github.event.head_commit.message, '[build]')
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Install rust targets for iOS
      run: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios

    - name: Cache rust
      uses: Swatinem/rust-cache@v2

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 15.4

    - name: Build
      run: make zip

    - name: Upload to release
      uses: IsaacShelton/update-existing-release@v1.3.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: "Build"
        tag: "build"
        files: |
          em_proxy.xcframework.zip
          em_proxy.h
          target/debug/libem_proxy-ios.a
          target/debug/libem_proxy-sim.a
        body: |
          Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
